when:
  - event: manual
  - event: push
    branch: master

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: phenomics-agent-backend
      tags: ${CI_BUILD_NUMBER}
      dry_run: true
      dockerfile: Dockerfile
      context: .

  - name: deploy
    image: docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - cd /home/root01/phenomics-agent
      - docker compose up -d --build phenomics-backend
      - docker image prune -f

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
